package com.onyem.jtracer.reader.meta;

import java.util.List;

import javax.annotation.Nullable;

public interface IMethod {

  MethodId getId();

  @Nullable
  Long getMetaId();

  // Flag Name        Value   Interpretation
  // ACC_PUBLIC       0x0001  Declared public; may be accessed from outside its package.
  // ACC_PRIVATE      0x0002  Declared private; accessible only within the defining class.
  // ACC_PROTECTED    0x0004  Declared protected; may be accessed within subclasses.
  // ACC_STATIC       0x0008  Declared static.
  // ACC_FINAL        0x0010  Declared final; may not be overridden.
  // ACC_SYNCHRONIZED 0x0020  Declared synchronized; invocation is wrapped in a monitor lock.
  // ACC_BRIDGE       0x0040  A bridge method, generated by the compiler.
  // ACC_VARARGS      0x0080  Declared with variable number of arguments.
  // ACC_NATIVE       0x0100  Declared native; implemented in a language other than Java.
  // ACC_ABSTRACT     0x0400  Declared abstract; no implementation is provided.
  // ACC_STRICT       0x0800  Declared strictfp; floating-point mode is FP-strict
  // ACC_SYNTHETIC    0x1000  Declared synthetic; not present in the source code. 
  @Nullable
  Integer getAccess();

  String getName();

  ClassId getIClass();

  List<ClassId> getParameters();

  ClassId getReturn();

  List<ClassId> getExceptions();

  String getCanonicalDescription();

  @Nullable
  // null if the method parameters, return type and exceptions do not use generic types
  String getCanonicalSignature();

}
