-- Classes table
CREATE TABLE CLASSES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  META_ID BIGINT,
  ACCESS INT,
  -- Name contains the class name like Object
  NAME VARCHAR(512),
  -- PACKAGE contains the package name like foo.bar
  PACKAGE VARCHAR(512),
  SIGNATURE VARCHAR(1024),
  IS_CLASS BOOLEAN NOT NULL,
  IS_INTERFACE BOOLEAN NOT NULL,
  IS_PRIMITIVE BOOLEAN NOT NULL,
  IS_ARRAY BOOLEAN NOT NULL,
  SUPERCLASS_ID BIGINT,
  COMPONENT_ID BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (SUPERCLASS_ID) REFERENCES CLASSES(ID),
  FOREIGN KEY (COMPONENT_ID) REFERENCES CLASSES(ID)
);

CREATE INDEX CLASS_META_ID_INDEX ON CLASSES(META_ID);

INSERT INTO CLASSES (ID, NAME, IS_CLASS, IS_PRIMITIVE, IS_ARRAY, IS_INTERFACE) VALUES 
(1, 'void', 0, 1, 0, 0),
(2, 'byte', 0, 1, 0, 0),
(3, 'char', 0, 1, 0, 0),
(4, 'double', 0, 1, 0, 0),
(5, 'float', 0, 1, 0, 0),
(6, 'int', 0, 1, 0, 0),
(7, 'long', 0, 1, 0, 0),
(8, 'short', 0, 1, 0, 0),
(9, 'boolean', 0, 1, 0, 0);

-- Interfaces 
CREATE TABLE CLASS_INTERFACES (
  CLASS_ID BIGINT NOT NULL,
  INTERFACE_ID BIGINT,
  FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID),
  FOREIGN KEY (INTERFACE_ID) REFERENCES CLASSES(ID)
);

-- Methods
CREATE TABLE METHODS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  META_ID BIGINT,
  ACCESS INT,
  NAME VARCHAR(512) NOT NULL,
  CLASS_ID BIGINT NOT NULL,
  RETURN_ID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  SIGNATURE VARCHAR(1024),
  PRIMARY KEY (ID),
  FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID)
);

CREATE INDEX METHOD_META_ID_INDEX ON METHODS(META_ID);

-- Method parameter types
CREATE TABLE METHOD_PARAMETERS (
  METHOD_ID BIGINT NOT NULL,
  PARAMETER_ID BIGINT,
  FOREIGN KEY (METHOD_ID) REFERENCES METHODS(ID),
  FOREIGN KEY (PARAMETER_ID) REFERENCES CLASSES(ID)
);

-- Method exceptions
CREATE TABLE METHOD_EXCEPTIONS (
  METHOD_ID BIGINT NOT NULL,
  EXCEPTION_ID BIGINT,
  FOREIGN KEY (METHOD_ID) REFERENCES METHODS(ID),
  FOREIGN KEY (EXCEPTION_ID) REFERENCES CLASSES(ID)
);

UPDATE ONYEM SET VERSION = '0.2.0';
