-- Threads table
CREATE TABLE THREADS (
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
);

CREATE TABLE EVENT_FILES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(512),
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX EVENT_FILE_NAME_INDEX ON EVENT_FILES(NAME);

-- Super table of all Events
CREATE TABLE EVENTS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  EVENT_FILE_ID BIGINT NOT NULL,
  POSITION BIGINT NOT NULL,
  EVENT_TYPE CHAR(2) NOT NULL,
  THREAD_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (THREAD_ID) REFERENCES THREADS(ID),
  FOREIGN KEY (EVENT_FILE_ID) REFERENCES EVENT_FILES(ID)
);

CREATE TABLE EVENT_METHODS (
  EVENT_ID BIGINT NOT NULL,
  METHOD_ID BIGINT NOT NULL,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID),
  FOREIGN KEY (METHOD_ID) REFERENCES METHODS(ID)
);

-- Table for the First and Last event of an EventsFile
CREATE TABLE EVENT_FILE_EVENTS (
  ID BIGINT NOT NULL,
  FIRST_EVENT_ID BIGINT,
  LAST_EVENT_ID BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES EVENT_FILES(ID),
  FOREIGN KEY (FIRST_EVENT_ID) REFERENCES EVENTS(ID),
  FOREIGN KEY (LAST_EVENT_ID) REFERENCES EVENTS(ID)
);

UPDATE ONYEM SET VERSION = '0.3.0';
